### Leo los archivos de los subhalos

Concateno los 8 archivos: saco masas, posicion y radio

In [2]:
%%time
import gc
import joblib
import h5py
import numpy as np 


dir_path = '/store/clues/HESTIA/RE_SIMS/8192/GAL_FOR/17_11/output_2x2.5Mpc/groups_127/'

SubhMass = []
SubhPos  = []
# SubhMTy  = []
SubhR50  = []

for i in range(0,8):
    
    snap = h5py.File(dir_path + 'fof_subhalo_tab_127.'+ str('%s'%i) +'.hdf5','r')

    sub_mass = snap['Subhalo/SubhaloMass'][()]
    sub_pos  = snap['Subhalo/SubhaloPos'][()]
#     sub_mty  = snap['Subhalo/SubhaloMassType'][()]
    sub_r50  = snap['Subhalo/SubhaloHalfmassRad'][()]

    SubhMass.append(sub_mass)
    SubhPos.append(sub_pos)
#     SubhMTy.append(sub_mty)
    SubhR50.append(sub_r50)

SubhMass = np.concatenate(SubhMass)
SubhPos  = np.concatenate(SubhPos)
# SubhMTy  = np.concatenate(SubhMTy)
SubhR50  = np.concatenate(SubhR50)

gc.collect()

CPU times: user 149 ms, sys: 87.3 ms, total: 236 ms
Wall time: 259 ms


0

#### Los ordeno por masa, saco los 10 mas masivos

In [3]:
import numpy as np

print (np.shape(SubhPos))

sort = np.argsort(SubhMass)

SMass = SubhMass[sort][::-1]*1e10
# SMTy  = SubhMTy[sort][::-1]*1e10
SR50  = SubhR50[sort][::-1]

print (SMass[:10])
# print (SMTy[:10])
print (SR50[:10])

(81461, 3)
[1.5752759e+12 1.1699873e+12 5.7578933e+11 5.5521280e+11 2.3570245e+11
 1.8116307e+11 1.6131521e+11 1.4867379e+11 1.4413586e+11 1.4381996e+11]
[0.06842346 0.04551199 0.05081347 0.0416441  0.02460471 0.01982324
 0.02079998 0.02245608 0.02539282 0.02286837]


#### Posiciones de los 10 mas masivos 

In [4]:
H_pos = SubhPos[sort][::-1]
print (H_pos[:10,:])

[[48.81521  46.704514 53.605064]
 [48.71576  47.06235  53.33718 ]
 [46.974728 49.455475 51.771206]
 [47.528534 46.364803 54.832882]
 [47.325207 47.259197 51.91327 ]
 [47.791496 47.55743  53.327   ]
 [47.41012  48.306732 52.663097]
 [49.867104 47.25419  52.225414]
 [45.62381  46.928238 54.103687]
 [48.525105 48.03401  51.99552 ]]


#### Leo las particulas del snapshot 

In [1]:
import numpy as np
path = '/store/clues/HESTIA/RE_SIMS/8192/GAL_FOR/17_11/AHF_output_2x2.5Mpc/'
data = np.loadtxt(path + 'HESTIA_100Mpc_8192_17_11.127.z0.000.AHF_halos')

ID   = data[:,0]
Mvir = data[:,3]
Xc   = data[:,5]
Yc   = data[:,6]
Zc   = data[:,7]
Rvir = data[:,11]
fMhires = data[:,37]

hires = np.where(fMhires > 0.9999)
IDs   = ID[hires]
M_vir = Mvir[hires]
X_c   = Xc[hires]
Y_c   = Yc[hires]
Z_c   = Zc[hires]
R_vir = Rvir[hires]

mask = np.argsort(M_vir)

MVir_AHF = M_vir[mask][::-1]
RVir_AHF = R_vir[mask][::-1]
Id_AHF   = IDs[mask][::-1]
Xc_AHF   = X_c[mask][::-1]
Yc_AHF   = Y_c[mask][::-1]
Zc_AHF   = Z_c[mask][::-1]

In [2]:
%%time
import gc
import joblib
import h5py
import pathlib
import numpy as np

dir_path = '/store/clues/HESTIA/RE_SIMS/8192/GAL_FOR/17_11/output_2x2.5Mpc/snapdir_127/'

StrPos  = []
StrMass = []

GasPos  = []
GasMass = []

DrkPos  = []
DrkMass = []


for i in range(0,8):
    snap = h5py.File(dir_path + 'snapshot_127.'+ str('%s'%i) +'.hdf5','r')
    
    #stars
    pos_str    = snap['PartType4/Coordinates'][()]
    mass_str   = snap['PartType4/Masses'][()]
   
    StrPos.append(pos_str)
    StrMass.append(mass_str)

    #gas
    pos_gas    = snap['PartType0/Coordinates'][()]
    mass_gas   = snap['PartType0/Masses'][()]
    
    GasPos.append(pos_gas)
    GasMass.append(mass_gas)

    #dark matter
    pos_drk    = snap['PartType1/Coordinates'][()]
    mass_drk   = snap['PartType1/Masses'][()]
    
    DrkPos.append(pos_drk)
    DrkMass.append(mass_drk)

    
a = snap.get('Header').attrs['Time']
h = snap.get('Header').attrs['HubbleParam']

Omega0   = snap.get('Header').attrs['Omega0']
Omegab   = snap.get('Header').attrs['OmegaBaryon']
OmegaL   = snap.get('Header').attrs['OmegaLambda']
Redshift = snap.get('Header').attrs['Redshift']

Unit_Length = snap.get('Header').attrs['UnitLength_in_cm']
Unit_Mass   = snap.get('Header').attrs['UnitMass_in_g']
Unit_Veloc  = snap.get('Header').attrs['UnitVelocity_in_cm_per_s']

StrPos  = np.concatenate(StrPos)
StrMass = np.concatenate(StrMass)

GasPos  = np.concatenate(GasPos)
GasMass = np.concatenate(GasMass)

DrkPos  = np.concatenate(DrkPos)
DrkMass = np.concatenate(DrkMass)

gc.collect()

CPU times: user 2.77 s, sys: 16.6 s, total: 19.4 s
Wall time: 24.4 s


0

#### Veo cuales son los subhalos que no tenian part low-res 

In [6]:
import numpy as np
subh = np.loadtxt('../_data/subhalos.dat')

halo_mask, = np.where((subh[:,15]==0) & (subh[:,16]==0))

subh_name = subh[:,0][halo_mask]
subh_ind  = np.int_(subh_name)
# nsubh = len(subh_name)

print(subh_ind)

[ 0  1  3  4  5  6  7  9 20 21 22 27 28 31 33 35 36 37 38 39 41 42 45 46
 49 50 51 53 54 64 65 66 69 73 74 79 84 85 87 88 90 91 92 95 96]


##### Aca me quedo con los primeros 8 halos 

### Calculo los Rvir y Mvir 

Guardo el archivo **Mvir_Rvir.dat**

In [5]:
%%time

import numpy as np
import gc

G = 4.299e-6 #kpc*(km/s)**2*Msol^-1

H0 = 100*h #km/s/Mpc

# omega_matter = results[0]['Omega0']
# omega_lambda = results[0]['OmegaL']
# omega0 = omega_matter + omega_lambda

# z = results[0]['Redshift']

path2 = '/home/omarioni/gradients/_data/'
archivo =  open(path2 + 'Mvir_Rvir_AHF.dat','a')

for i in range(15):
    

    xstr = (StrPos[:,0]*1000-Xc_AHF[i])*a/h
    ystr = (StrPos[:,1]*1000-Yc_AHF[i])*a/h
    zstr = (StrPos[:,2]*1000-Zc_AHF[i])*a/h
    rstr = np.sqrt(xstr**2 + ystr**2 + zstr**2)
    mstr = StrMass*1e10/h
    
    xgas = (GasPos[:,0]*1000-Xc_AHF[i])*a/h
    ygas = (GasPos[:,1]*1000-Yc_AHF[i])*a/h
    zgas = (GasPos[:,2]*1000-Zc_AHF[i])*a/h
    rgas = np.sqrt(xgas**2 + ygas**2 + zgas**2)
    mgas = GasMass*1e10/h
    
    xdrk = (DrkPos[:,0]*1000-Xc_AHF[i])*a/h
    ydrk = (DrkPos[:,1]*1000-Yc_AHF[i])*a/h
    zdrk = (DrkPos[:,2]*1000-Zc_AHF[i])*a/h
    rdrk = np.sqrt(xdrk**2 + ydrk**2 + zdrk**2)
    mdrk = DrkMass*1e10/h
    
    st, = np.where(rstr < 1000)
    dm, = np.where(rdrk < 1000)
    gs, = np.where(rstr < 1000)
    
    r = np.concatenate([rstr[st], rgas[gs], rdrk[dm]])
    m = np.concatenate([mstr[st], mgas[gs], mdrk[dm]])

    psort = np.argsort(r)
    
    
    vol  = 4./3 * np.pi * r[psort]**3
    mass = np.cumsum(m[psort])
    rho  = mass / vol

    H0_kpc = H0/1000 #paso a kpc
    
    rho_crit = 3.*H0_kpc**2 / (8.*np.pi*G)

    mask, = np.where(rho > 200*rho_crit)
    
    Mvir = mass[mask][-1]
    Rvir = r[psort][mask][-1] 
    
    print ('subhalo', str('%d'%Id_AHF[i]), 'Mvir = ', str('%.4E'%Mvir), 'Rvir = ', str('%4.8f'%Rvir))
    
    archivo.write(str('%03d'%Id_AHF[i] ) +'\t'+
                 str('%1.6E'% Mvir) +'\t'+
                 str('%12.6f'% Rvir) +'\n')

archivo.close()
    
gc.collect()


subhalo 127000000000002 Mvir =  2.6059E+12 Rvir =  290.01149917
subhalo 127000000000003 Mvir =  2.2134E+12 Rvir =  274.65242828
subhalo 127000000000004 Mvir =  7.9339E+11 Rvir =  195.10077761
subhalo 127000000000006 Mvir =  3.3978E+11 Rvir =  147.05952832
subhalo 127000000000007 Mvir =  2.6794E+11 Rvir =  135.86481884
subhalo 127000000000009 Mvir =  2.4268E+11 Rvir =  131.45309434
subhalo 127000000000012 Mvir =  1.9425E+11 Rvir =  122.05334483
subhalo 127000000000011 Mvir =  2.0015E+11 Rvir =  123.27558165
subhalo 127000000000014 Mvir =  1.2214E+11 Rvir =  104.56542229
subhalo 127000000000020 Mvir =  8.2075E+10 Rvir =  91.58588925
subhalo 127000000000021 Mvir =  7.9272E+10 Rvir =  90.53227168
subhalo 127000000000023 Mvir =  7.9543E+10 Rvir =  90.63468031
subhalo 127000000000028 Mvir =  5.3534E+10 Rvir =  79.42770409
subhalo 127000000000031 Mvir =  4.8143E+10 Rvir =  76.66483985
subhalo 127000000000030 Mvir =  2.0500E+12 Rvir =  267.72256251
CPU times: user 5min 18s, sys: 1min 55s, tota

0